# Default values for dance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

openshift-gitops:
  enabled: true
  channel: gitops-1.11
  argocd-namespace: dance-argocd
  workload-namespaces:
    - default
openshift-pipelines:
  enabled: true
  channel: pipelines-1.13
quay:
  enabled: true
  registry: quay.io
  username: admin
  password: admin

# Private values
# You may want to override those variables in another file (e.g. values-private.yaml)
# This is a copy of the helm, updated to use env vars and validate they all exist to simplify install.
# 
acs:
  central-endpoint: central.rhacs-operator.svc.cluster.local:443
  api-token: ${ROX_API_TOKEN}
developer-hub:
  app-config:
    auth:
      environment: development
      providers:
        github:
          development:
            clientId: ${MY_GITHUB_OATH_CLIENT}
            clientSecret: ${MY_GITHUB_OATH_SECRET}  
    integrations:
      github:
        - host: github.com
          apps:
            - appId: ${GITHUB_APP_APP_ID}
              clientId: ${GITHUB_APP_CLIENT_ID}
              clientSecret: ${GITHUB_APP_CLIENT_SECRET}
              webhookUrl: ${GITHUB_APP_WEBHOOK_URL}
              webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
              privateKey: |
                ${GITHUB_APP_PRIVATE_KEY}
    catalog:
      locations:
        - type: url
          target: https://github.com/redhat-appstudio/tssc-sample-templates/blob/main/all.yaml
      rules:
        - allow:
          - Component
          - System
          - Group
          - Resource
          - Location
          - Template
          - API
    # This should be removed once RHDH is GA
  # quay-token: eyAbC123...rhdh...890XyZ
pipelines:
  pipelines-as-code:
    github:
      application-id: 123456
      private-key: |
        Insert the private key data, including the '---- ... ----'
        header and footer.
      webhook-secret: ${WEBHOOK_SECRET}


